name: Tag Version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  release:
    name: Create Release Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git user info
        run: | 
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com" 

      - name: Tag the release
        id: tag-release
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Tagging release with version: $VERSION"
          git tag -a "$VERSION" -m "Release version $VERSION"
          git push origin "$VERSION"
          echo "version=$version" >> $GITHUB_OUTPUT

  github-release:
        name: Create github release
        needs: release
        runs-on: ubuntu-latest

        permissions:
          contents: write

        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Fetch tags
            run: git fetch --tags

          - name: Get latest tag
            id: tag
            run: echo "latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

          - name: Create Github release
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              tag: ${{ steps.tag.outputs.latest_tag }}
            run: |
                gh release create $tag \
                    --repo="$GITHUB_REPOSITORY" \
                    --title="Release for $tag" \
                    --generate-notes
              
        